### ISSUE TITLE
Support the inclusion of en_NL in glibc. Updating /etc/locale.conf.

### ISSUE THREAD

**Issue by BobbyBabes** [PanderMusubi/locale-en-nl#1]
Thanks for your efforts with this subject.

I have some questions.
(1) I added myself sometime ago to the ``CC List`` at the Sourceware Bugzilla website. Is that the proper way to support the inclusion of en_NL in glibc ?
(2) Why does the installer script not overwrite the locale setting in ``/etc/locale.conf`` ?

**Comment by PanderMusubi** [comment]
The installer script will be updated soon. In order to show your support for this, please leave a useful comment at https://sourceware.org/bugzilla/show_bug.cgi?id=14085
