### ISSUE TITLE
How do I install this on Fedora?

### ISSUE THREAD

**Issue by sylvesterroos** [PanderMusubi/locale-en-nl#5]

**Comment by PanderMusubi** [comment]
No idea, but if you find out, please share so I can add it to the README.

**Comment by sylvesterroos** [comment]
I'll see what I can do 🙂

**Comment by sylvesterroos** [comment]
Okay I'm back with the how-to

1. Install the `glibc-locale-source` package
2. Run `# localedef --no-archive --inputfile=en_NL --charmap=UTF-8 en_NL.UTF-8` inside the cloned directory
(The UTF-8 file is provided by the package)
This will create the compiled locale files under `/usr/lib/locale/en_NL.utf8/`
3. Profit!

**Comment by PanderMusubi** [comment]
Added to README.md
